binocular {
  bitcoin-node {
    url = ""
    url = ${?bitcoind_rpc_url}
    url = ${?BITCOIN_NODE_URL}
    username = ""
    username = ${?bitcoind_rpc_user}
    username = ${?BITCOIN_NODE_USER}
    password = ""
    password = ${?bitcoind_rpc_password}
    password = ${?BITCOIN_NODE_PASSWORD}
    network = "mainnet"
    network = ${?BITCOIN_NETWORK}
  }

  cardano {
    network = "mainnet"
    network = ${?CARDANO_NETWORK}
    backend = "blockfrost"
    backend = ${?CARDANO_BACKEND}
    blockfrost-project-id = ""
    blockfrost-project-id = ${?BLOCKFROST_PROJECT_ID}
    yaci-store-url = "http://localhost:8080/api/v1"
    yaci-store-url = ${?YACI_STORE_URL}
    yaci-admin-url = "http://localhost:10000/local-cluster/api"
    yaci-admin-url = ${?YACI_ADMIN_URL}
  }

  wallet {
    mnemonic = ""
    mnemonic = ${?WALLET_MNEMONIC}
  }

  oracle {
    tx-out-ref = ""
    tx-out-ref = ${?ORACLE_TX_OUT_REF}
    owner-pkh = ""
    owner-pkh = ${?ORACLE_OWNER_PKH}
    start-height = null
    start-height = ${?ORACLE_START_HEIGHT}
    max-headers-per-tx = 10
    max-headers-per-tx = ${?ORACLE_MAX_HEADERS_PER_TX}
    poll-interval = 1
    poll-interval = ${?ORACLE_POLL_INTERVAL}
    retry-interval = 10
    retry-interval = ${?ORACLE_RETRY_INTERVAL}
    transaction-timeout = 120
    transaction-timeout = ${?ORACLE_TRANSACTION_TIMEOUT}
  }
}
