package binocular.blueprint

import scalus.cardano.blueprint.{Blueprint, DataType, PlutusDataSchema, Preamble, TypeDescription, Validator}
import scalus.cardano.ledger.Script
import scalus.uplc.builtin.{ByteString, Data}
import scalus.uplc.{Constant, PlutusV3, Program, Term}
import scalus.utils.Hex.toHex

/** Loads binocular's validators from the CIP-57 blueprints generated by the scalus-sbt-plugin
  * `blueprint` task (one `META-INF/scalus/blueprints/<ContractName>.json` per
  * [[scalus.cardano.blueprint.Contract]] implementation, embedded in the jar as resources).
  *
  * Parameter application happens at the UPLC level — `Program $ constant` — exactly like
  * `aiken blueprint apply` / Blaze `applyParamsToScript` (and like
  * [[binocular.watchtower.BifrostBlueprint]] does for the Aiken bridge validators). This means
  * every deployed script hash is reproducible from the published blueprint JSON alone with standard
  * Cardano tooling; no Scalus compiler invocation (or version) is involved at load time.
  *
  * Application must mirror the compiled validator's shape: a validator compiled from
  * `(p: Data) => ...` takes a `Data` constant, one compiled from `(p: ByteString) => ...` takes a
  * bare UPLC bytestring constant.
  */
object BinocularBlueprint {

    /** Classpath directory the scalus-sbt-plugin writes generated blueprints into. */
    private val ResourceDir = "/META-INF/scalus/blueprints"

    private def load(contractName: String): Blueprint = {
        val path = s"$ResourceDir/$contractName.json"
        val stream = getClass.getResourceAsStream(path)
        if stream == null then
            throw new IllegalStateException(
              s"Blueprint resource $path not found on the classpath — run `sbt blueprint` " +
                  "(it runs as part of `resources`/`package`) and rebuild"
            )
        try Blueprint.fromJson(stream)
        finally stream.close()
    }

    /** The unapplied compiled program of `contractName`'s single validator. */
    def program(contractName: String): Program = {
        val bp = load(contractName)
        val code = bp.validators.headOption
            .flatMap(_.compiledCode)
            .getOrElse(
              throw new IllegalStateException(
                s"Blueprint $contractName has no validator compiledCode"
              )
            )
        Program.fromCborHex(code)
    }

    /** Loads a param-free validator verbatim. */
    def script(contractName: String): Script.PlutusV3 =
        Script.PlutusV3(program(contractName).cborByteString)

    /** Loads a validator and applies `params` at the UPLC level, in declaration order. */
    def script(contractName: String, params: Term*): Script.PlutusV3 =
        Script.PlutusV3(params.foldLeft(program(contractName))(_ $ _).cborByteString)

    /** A `Data` parameter term (for validators declared over `Data` params). */
    def dataParam(d: Data): Term = Term.Const(Constant.Data(d))

    /** A bare bytestring parameter term (for validators declared over `ByteString` params). */
    def bytesParam(bs: ByteString): Term = Term.Const(Constant.ByteString(bs))

    /** CIP-57 description of an opaque `Data` redeemer/datum: an empty schema matches any Plutus
      * data. Used where the validator parses the raw `Data` itself (no derivable schema).
      */
    val opaqueDataDescription: TypeDescription = TypeDescription(
      title = Some("Data"),
      description = Some("Any Plutus data"),
      purpose = None,
      schema = PlutusDataSchema()
    )

    /** CIP-57 description of a bare `ByteString` validator parameter. */
    val bytesParamDescription: TypeDescription = TypeDescription(
      title = Some("ByteString"),
      description = None,
      purpose = None,
      schema = PlutusDataSchema(dataType = Some(DataType.Bytes))
    )

    /** Blueprint for a param-free validator over an opaque `Data` redeemer. */
    def paramFreeBlueprint(
        title: String,
        description: String,
        compiled: PlutusV3[Data => Unit]
    ): Blueprint =
        Blueprint(
          preamble = Preamble(
            title,
            description,
            "1.0.0",
            plutusVersion = compiled.language,
            license = Some("Apache-2.0")
          ),
          validators = Seq(
            Validator(
              title = title,
              description = Some(description),
              redeemer = Some(opaqueDataDescription),
              datum = None,
              parameters = None,
              compiledCode = Some(compiled.program.cborEncoded.toHex),
              hash = Some(compiled.script.scriptHash.toHex)
            )
          )
        )
}
